# Generated by Django 3.0.5 on 2020-04-29 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('_image_hash', models.BinaryField(default=None, max_length=16, null=True)),
                ('thumbnail', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('_thumbnail_hash', models.BinaryField(default=None, max_length=16, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
