# Generated by Django 3.1.5 on 2021-01-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200626_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
