# Generated by Django 3.0.7 on 2020-08-01 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20200729_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='family_first',
            new_name='surname_first',
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Contact'),
        ),
    ]
