# Generated by Django 3.1 on 2020-08-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20200804_1741'),
        ('quotes', '0003_auto_20200801_1226'),
    ]

    operations = [
    ]
